import { useEffect,useMemo,useState,type FormEvent } from "react";
import "./App.css";

type TxType="income"|"expense"; type Main="info"|"loans"|"calendar"|"notes"; type Info="overview"|"budget"|"canbuy"; type LoanTab="cashout"|"cashin"; type CalTab="calendar"|"todo";
type Tx={id:string;name:string;amount:number;type:TxType;date:string;category:string}; type Debt={id:string;name:string;balance:number;minimumPayment:number;interest:number;dueDate:string;priority:number}; type Payment={id:string;debtId:string;debtName:string;amount:number;date:string}; type Task={id:string;title:string;date:string;completed:boolean}; type Receivable={id:string;name:string;amount:number;dueDate:string;note:string}; type Note={id:string;title:string;text:string;created:string}; type Settings={startingBalance:number;monthlyReserve:number}; type Data={transactions:Tx[];debts:Debt[];debtPayments:Payment[];tasks:Task[];receivables:Receivable[];notes:Note[];settings:Settings};
const KEY="rebuildme-mymoney-v3",OLD="rebuildme-mymoney-v2",today=()=>new Date().toISOString().slice(0,10),id=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`,eur=(n:number)=>new Intl.NumberFormat("et-EE",{style:"currency",currency:"EUR"}).format(n),num=(v:string|number)=>typeof v==="number"?v:(Number(v.trim().replace(/\s/g,"").replace(",","."))||0);
const empty:Data={transactions:[],debts:[],debtPayments:[],tasks:[],receivables:[],notes:[],settings:{startingBalance:0,monthlyReserve:100}};
function norm(v:any):Data{return {...empty,...v,transactions:Array.isArray(v?.transactions)?v.transactions:[],debts:Array.isArray(v?.debts)?v.debts:[],debtPayments:Array.isArray(v?.debtPayments)?v.debtPayments:[],tasks:Array.isArray(v?.tasks)?v.tasks:[],receivables:Array.isArray(v?.receivables)?v.receivables:[],notes:Array.isArray(v?.notes)?v.notes:[],settings:{startingBalance:Number(v?.settings?.startingBalance)||0,monthlyReserve:Number(v?.settings?.monthlyReserve)||100}}}

export default function App(){
 const [main,setMain]=useState<Main>("info"),[info,setInfo]=useState<Info>("overview"),[loan,setLoan]=useState<LoanTab>("cashout"),[cal,setCal]=useState<CalTab>("calendar");
 const [data,setData]=useState<Data>(()=>{try{return norm(JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD)||"null"))}catch{return empty}});
 const [quick,setQuick]=useState<TxType|null>(null),[amount,setAmount]=useState(""),[name,setName]=useState(""),[category,setCategory]=useState("Muu");
 const [buy,setBuy]=useState(""),[debtName,setDebtName]=useState(""),[debtBalance,setDebtBalance]=useState(""),[debtMin,setDebtMin]=useState(""),[debtDue,setDebtDue]=useState(today());
 const [recName,setRecName]=useState(""),[recAmount,setRecAmount]=useState(""),[recDue,setRecDue]=useState(today()),[task,setTask]=useState(""),[taskDate,setTaskDate]=useState(today()),[noteTitle,setNoteTitle]=useState(""),[noteText,setNoteText]=useState("");
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(data)),[data]);
 const month=today().slice(0,7),mTx=data.transactions.filter(x=>x.date.startsWith(month)),income=mTx.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),expenses=mTx.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0),balance=data.settings.startingBalance+income-expenses,debtPlan=data.debts.reduce((s,x)=>s+x.minimumPayment,0),debtPaid=data.debtPayments.filter(x=>x.date.startsWith(month)).reduce((s,x)=>s+x.amount,0),safe=balance-Math.max(0,debtPlan-debtPaid)-data.settings.monthlyReserve;
 const todays=data.transactions.filter(x=>x.date===today()),todayIn=todays.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),todayOut=todays.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0),days=Math.max(1,new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate()-new Date().getDate()+1),daily=Math.max(0,safe/days),buyValue=num(buy),after=safe-buyValue;
 const timeline=useMemo(()=>[...data.tasks.map(x=>({id:"t"+x.id,date:x.date,title:(x.completed?"✓ ":"")+x.title,detail:"To-Do"})),...data.debts.map(x=>({id:"d"+x.id,date:x.dueDate,title:x.name,detail:`Cash Out · ${eur(x.balance)}`})),...data.receivables.map(x=>({id:"r"+x.id,date:x.dueDate,title:x.name,detail:`Cash In · ${eur(x.amount)}`}))].sort((a,b)=>a.date.localeCompare(b.date)),[data]);
 function addTx(e:FormEvent){e.preventDefault();const a=num(amount);if(a<=0||!quick)return;setData(d=>({...d,transactions:[{id:id(),name:name.trim()||(quick==="expense"?"Kulu":"Tulu"),amount:a,type:quick,date:today(),category},...d.transactions]}));setAmount("");setName("");setQuick(null)}
 function addDebt(e:FormEvent){e.preventDefault();const a=num(debtBalance);if(!debtName.trim()||a<=0)return;setData(d=>({...d,debts:[...d.debts,{id:id(),name:debtName.trim(),balance:a,minimumPayment:num(debtMin),interest:0,dueDate:debtDue,priority:d.debts.length+1}]}));setDebtName("");setDebtBalance("");setDebtMin("")}
 function addRec(e:FormEvent){e.preventDefault();const a=num(recAmount);if(!recName.trim()||a<=0)return;setData(d=>({...d,receivables:[...d.receivables,{id:id(),name:recName.trim(),amount:a,dueDate:recDue,note:""}]}));setRecName("");setRecAmount("")}
 function addTask(e:FormEvent){e.preventDefault();if(!task.trim())return;setData(d=>({...d,tasks:[...d.tasks,{id:id(),title:task.trim(),date:taskDate,completed:false}]}));setTask("")}
 function addNote(e:FormEvent){e.preventDefault();if(!noteTitle.trim()&&!noteText.trim())return;setData(d=>({...d,notes:[{id:id(),title:noteTitle.trim()||"Märge",text:noteText.trim(),created:today()},...d.notes]}));setNoteTitle("");setNoteText("")}
 return <div className="app-shell"><header className="topbar"><div><p className="eyebrow">MyMoney</p><h1>{main==="info"?"Info":main==="loans"?"Loans":main==="calendar"?"Calendar":"Notes"}</h1></div><button className="secondary-button" onClick={()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`mymoney-${today()}.json`;a.click();URL.revokeObjectURL(u)}}>Backup</button></header>
 <nav className="navigation"><Nav t="Info" a={main==="info"} f={()=>setMain("info")}/><Nav t="Loans" a={main==="loans"} f={()=>setMain("loans")}/><Nav t="Calendar" a={main==="calendar"} f={()=>setMain("calendar")}/><Nav t="Notes" a={main==="notes"} f={()=>setMain("notes")}/></nav>
 <main>{main==="info"&&<><Sub items={[["Overview",info==="overview",()=>setInfo("overview")],["Budget",info==="budget",()=>setInfo("budget")],["Can I buy it?",info==="canbuy",()=>setInfo("canbuy")]]}/>
 {info==="overview"&&<><section className="summary-grid"><Card l="Saldo" v={eur(balance)} d="Praegune"/><Card l="Täna sisse" v={"+"+eur(todayIn)} d="Tänased tulud"/><Card l="Täna välja" v={"−"+eur(todayOut)} d="Tänased kulud"/><Card l="Turvaliselt kasutada" v={eur(Math.max(0,safe))} d={`Päevas ${eur(daily)}`}/></section><section className="card"><div className="section-heading"><div><p className="eyebrow">Kiire sisestus</p><h2>Tänane raha</h2></div></div><div className="quick-actions"><button className="primary-button" onClick={()=>setQuick("expense")}>− Expense</button><button className="primary-button" onClick={()=>setQuick("income")}>+ Income</button></div>{quick&&<form onSubmit={addTx} className="quick-form"><Money label="Summa" value={amount} set={setAmount} focus/><label>Nimetus (valikuline)<input value={name} onChange={e=>setName(e.target.value)} placeholder={quick==="expense"?"nt Toit":"nt Palk"}/></label><label>Kategooria<select value={category} onChange={e=>setCategory(e.target.value)}><option>Muu</option><option>Toit</option><option>Transport</option><option>Elamine</option><option>Töö</option><option>Sissetulek</option></select></label><button className="primary-button">Save</button></form>}</section><section className="card"><h2>Täna</h2>{todays.length?todays.map(x=><Row key={x.id} title={x.name} sub={x.category} right={(x.type==="income"?"+":"−")+eur(x.amount)}/>):<Empty t="Täna pole veel kirjeid."/>}</section></>}
 {info==="budget"&&<><section className="summary-grid"><Card l="Kuu tulud" v={eur(income)} d="Income"/><Card l="Kuu kulud" v={eur(expenses)} d="Expenses"/><Card l="Võlamaksed" v={eur(debtPaid)} d={`Plaan ${eur(debtPlan)}`}/><Card l="Turvaliselt kasutada" v={eur(safe)} d="Pärast reservi"/></section><section className="card"><h2>Budget settings</h2><div className="form-grid"><Setting label="Algjääk" value={data.settings.startingBalance} save={v=>setData(d=>({...d,settings:{...d.settings,startingBalance:num(v)}}))}/><Setting label="Turvareserv" value={data.settings.monthlyReserve} save={v=>setData(d=>({...d,settings:{...d.settings,monthlyReserve:num(v)}}))}/></div></section></>}
 {info==="canbuy"&&<section className="card"><p className="eyebrow">Can I buy it?</p><h2>Kas see mahub eelarvesse?</h2><Money label="How much?" value={buy} set={setBuy} focus/><div className={`affordability ${buyValue<=0?"neutral":after>=0?"good":"danger"}`}><strong>{buyValue<=0?"Sisesta hind":after>=0?"YES":"NO"}</strong><span>{buyValue<=0?"Arvutan kohe sinu praeguse eelarve järgi.":after>=0?`Pärast ostu jääb ${eur(after)}.`:`Puudu jääb ${eur(Math.abs(after))}.`}</span></div></section>}</>}
 {main==="loans"&&<><Sub items={[["Cash Out",loan==="cashout",()=>setLoan("cashout")],["Cash In",loan==="cashin",()=>setLoan("cashin")]]}/>{loan==="cashout"?<><section className="summary-grid"><Card l="Mina võlgu" v={eur(data.debts.reduce((s,x)=>s+x.balance,0))} d={`${data.debts.length} võlga`}/><Card l="Kuu plaan" v={eur(debtPlan)} d="Maksta"/></section><section className="card"><h2>Lisa Cash Out</h2><form onSubmit={addDebt} className="form-grid wide"><label>Kellele<input required value={debtName} onChange={e=>setDebtName(e.target.value)}/></label><Money label="Jääk" value={debtBalance} set={setDebtBalance}/><Money label="Kuumakse" value={debtMin} set={setDebtMin}/><label>Tähtaeg<input type="date" value={debtDue} onChange={e=>setDebtDue(e.target.value)}/></label><button className="primary-button">Lisa</button></form></section><section className="card">{data.debts.length?data.debts.map(x=><Row key={x.id} title={x.name} sub={`Tähtaeg ${x.dueDate} · kuumakse ${eur(x.minimumPayment)}`} right={eur(x.balance)}/>):<Empty t="Cash Out on tühi."/>}</section></>:<><section className="summary-grid"><Card l="Mulle võlgu" v={eur(data.receivables.reduce((s,x)=>s+x.amount,0))} d={`${data.receivables.length} kirjet`}/></section><section className="card"><h2>Lisa Cash In</h2><form onSubmit={addRec} className="form-grid"><label>Kes võlgneb<input required value={recName} onChange={e=>setRecName(e.target.value)}/></label><Money label="Summa" value={recAmount} set={setRecAmount}/><label>Tähtaeg<input type="date" value={recDue} onChange={e=>setRecDue(e.target.value)}/></label><button className="primary-button">Lisa</button></form></section><section className="card">{data.receivables.length?data.receivables.map(x=><Row key={x.id} title={x.name} sub={`Tähtaeg ${x.dueDate}`} right={eur(x.amount)}/>):<Empty t="Cash In on tühi."/>}</section></>}</>}
 {main==="calendar"&&<><Sub items={[["Calendar",cal==="calendar",()=>setCal("calendar")],["To-Do",cal==="todo",()=>setCal("todo")]]}/>{cal==="calendar"?<section className="card"><h2>Calendar</h2>{timeline.length?timeline.map(x=><Row key={x.id} title={x.title} sub={`${x.date} · ${x.detail}`} right=""/>):<Empty t="Kalender on tühi."/>}</section>:<><section className="card"><h2>Lisa To-Do</h2><form onSubmit={addTask} className="form-grid"><label>Ülesanne<input required value={task} onChange={e=>setTask(e.target.value)}/></label><label>Kuupäev<input type="date" value={taskDate} onChange={e=>setTaskDate(e.target.value)}/></label><button className="primary-button">Lisa</button></form></section><section className="card">{data.tasks.length?data.tasks.map(x=><div className={`list-row ${x.completed?"completed":""}`} key={x.id}><button className="check-button" onClick={()=>setData(d=>({...d,tasks:d.tasks.map(t=>t.id===x.id?{...t,completed:!t.completed}:t)}))}>{x.completed?"✓":"○"}</button><div className="list-content"><strong>{x.title}</strong><span>{x.date}</span></div></div>):<Empty t="To-Do on tühi."/>}</section></>}</>}
 {main==="notes"&&<><section className="card"><h2>Uus märge</h2><form onSubmit={addNote}><div className="form-grid"><label>Pealkiri<input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/></label></div><label>Märge<textarea value={noteText} onChange={e=>setNoteText(e.target.value)} rows={5}/></label><button className="primary-button">Save note</button></form></section><section className="card">{data.notes.length?data.notes.map(n=><article className="note-card" key={n.id}><small>{n.created}</small><h3>{n.title}</h3><p>{n.text}</p></article>):<Empty t="Märkmeid pole veel."/>}</section></>}
 </main></div>
}
function Nav({t,a,f}:{t:string;a:boolean;f:()=>void}){return <button className={`nav-button ${a?"active":""}`} onClick={f}>{t}</button>}
function Sub({items}:{items:[string,boolean,()=>void][]}){return <div className="subnav">{items.map(([t,a,f])=><button key={t} className={`subnav-button ${a?"active":""}`} onClick={f}>{t}</button>)}</div>}
function Card({l,v,d}:{l:string;v:string;d:string}){return <article className="summary-card"><span>{l}</span><strong>{v}</strong><small>{d}</small></article>}
function Money({label,value,set,focus=false}:{label:string;value:string;set:(v:string)=>void;focus?:boolean}){return <label>{label}<div className="money-wrap"><input autoFocus={focus} inputMode="decimal" value={value} onFocus={e=>e.currentTarget.select()} onChange={e=>set(e.target.value.replace(/[^0-9.,\-\s]/g,""))} placeholder="0,00"/><span>€</span></div></label>}
function Setting({label,value,save}:{label:string;value:number;save:(v:string)=>void}){const[d,setD]=useState(String(value).replace(".",","));return <label>{label}<div className="money-wrap"><input inputMode="decimal" value={d} onFocus={e=>e.currentTarget.select()} onChange={e=>setD(e.target.value.replace(/[^0-9.,\-\s]/g,""))} onBlur={()=>save(d)}/><span>€</span></div></label>}
function Row({title,sub,right}:{title:string;sub:string;right:string}){return <div className="list-row"><div className="list-content"><strong>{title}</strong><span>{sub}</span></div>{right&&<strong>{right}</strong>}</div>}
function Empty({t}:{t:string}){return <div className="empty-state">{t}</div>}
