import { useMemo, useState, type FormEvent } from "react";

const RECEIVABLES_KEY="rebuildme-mymoney-receivables-v1",STORAGE_KEY="rebuildme-mymoney-v2";
type Payment={id:string;amount:number;date:string;transactionId:string};
type Item={id:string;name:string;amount:number;dueDate:string;note?:string;status:"open"|"paid";paidDate?:string;payments?:Payment[]};
const euro=(v:number)=>new Intl.NumberFormat("en-FI",{style:"currency",currency:"EUR"}).format(v),today=()=>new Date().toISOString().slice(0,10),id=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function readItems():Item[]{try{const v=JSON.parse(localStorage.getItem(RECEIVABLES_KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function readMain(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")||{}}catch{return{}}}
function paid(i:Item){return Array.isArray(i.payments)?i.payments.reduce((s,p)=>s+Number(p.amount||0),0):0}
function left(i:Item){return Math.max(0,Number(i.amount||0)-paid(i))}

export default function Receivables(){
 const [items,setItems]=useState<Item[]>(readItems),[name,setName]=useState(""),[amount,setAmount]=useState(""),[dueDate,setDueDate]=useState(today()),[note,setNote]=useState("");
 const open=useMemo(()=>items.filter(i=>left(i)>0).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[items]);
 const total=open.reduce((s,i)=>s+left(i),0),overdue=open.filter(i=>i.dueDate<today()).length;
 function save(next:Item[]){setItems(next);localStorage.setItem(RECEIVABLES_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent("mymoney-data-changed"))}
 function add(e:FormEvent){e.preventDefault();const v=Number(amount.replace(",","."));if(!name.trim()||!Number.isFinite(v)||v<=0)return;save([{id:id(),name:name.trim(),amount:v,dueDate,note:note.trim()||undefined,status:"open",payments:[]},...items]);setName("");setAmount("");setNote("")}
 function receive(item:Item,value:number){const remaining=left(item),received=Math.min(value,remaining);if(received<=0)return;const main=readMain(),transactions=Array.isArray(main.transactions)?main.transactions:[],date=today(),transactionId=id(),payment={id:id(),amount:received,date,transactionId};localStorage.setItem(STORAGE_KEY,JSON.stringify({...main,transactions:[{id:transactionId,name:`Received: ${item.name}`,amount:received,type:"income",date,category:"Income",receivableId:item.id},...transactions]}));const nextPayments=[...(item.payments||[]),payment],fully=nextPayments.reduce((s,p)=>s+p.amount,0)>=item.amount-.005;save(items.map(x=>x.id===item.id?{...x,payments:nextPayments,status:fully?"paid":"open",paidDate:fully?date:undefined}:x))}
 function partial(item:Item){const answer=window.prompt(`Amount received\nRemaining: ${euro(left(item))}`,String(left(item).toFixed(2)));if(answer===null)return;const v=Number(answer.replace(",","."));if(Number.isFinite(v)&&v>0)receive(item,v)}
 function remove(item:Item){if(window.confirm("Delete this Cash In item?"))save(items.filter(x=>x.id!==item.id))}
 return <div className="receivables-tool"><div className="receivables-summary-grid"><article><span>Cash In total</span><strong>{euro(total)}</strong></article><article><span>Open</span><strong>{open.length}</strong></article><article><span>Overdue</span><strong className={overdue?"negative-text":"positive-text"}>{overdue}</strong></article></div><section className="card compact-form-card"><div className="section-heading"><div><p className="eyebrow">Cash In</p><h2>Add money owed to you</h2></div></div><form onSubmit={add}><div className="form-grid wide"><label>Who owes you<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Amount<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.,\s-]/g,""))}/></label><label>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><button className="primary-button">Add Cash In</button></form></section><section className="card"><div className="section-heading"><div><p className="eyebrow">Cash In</p><h2>Waiting for payment</h2></div></div>{open.length===0?<div className="empty-state">No open Cash In items.</div>:<div className="receivables-list">{open.map(item=><article className={`receivable-row ${item.dueDate<today()?"late":""}`} key={item.id}><div><strong>{item.name}</strong><span>Due {item.dueDate}{item.note?` · ${item.note}`:""}</span>{paid(item)>0&&<span>Received {euro(paid(item))} · remaining {euro(left(item))}</span>}</div><div className="receivable-actions"><strong>{euro(left(item))}</strong><button className="primary-button small" onClick={()=>receive(item,left(item))}>Received all</button><button className="secondary-button small" onClick={()=>partial(item)}>Partial</button><button className="danger-link" onClick={()=>remove(item)}>Delete</button></div></article>)}</div>}</section></div>
}
