import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

const STORAGE_KEY="rebuildme-mymoney-v2",PLANNED_KEY="rebuildme-mymoney-planned-v1",RECEIVABLES_KEY="rebuildme-mymoney-receivables-v1";
const euro=(v:number)=>new Intl.NumberFormat("en-FI",{style:"currency",currency:"EUR"}).format(v);
const today=()=>new Date().toISOString().slice(0,10);
function read(key:string,fallback:any){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function daysUntil(date:string){const a=new Date(today()+"T00:00:00"),b=new Date(date+"T00:00:00");return Math.round((b.getTime()-a.getTime())/86400000)}

export default function TodayOverview(){
 const [mount,setMount]=useState<HTMLElement|null>(null),[visible,setVisible]=useState(true),[revision,setRevision]=useState(0),[more,setMore]=useState(false);
 useEffect(()=>{const main=document.querySelector("main");if(!(main instanceof HTMLElement))return;const node=document.createElement("div");node.className="today-overview-mount";main.prepend(node);setMount(node);const update=()=>{const active=document.querySelector(".navigation .nav-button.active");setVisible(active?.textContent?.trim()==="Täna")};const refresh=()=>setRevision(v=>v+1);const nav=document.querySelector(".navigation");const click=()=>requestAnimationFrame(()=>{update();refresh()});update();nav?.addEventListener("click",click);window.addEventListener("mymoney-data-changed",refresh);return()=>{nav?.removeEventListener("click",click);window.removeEventListener("mymoney-data-changed",refresh);node.remove()}},[]);
 const s=useMemo(()=>{void revision;const data=read(STORAGE_KEY,{}),planned=read(PLANNED_KEY,[]),receivables=read(RECEIVABLES_KEY,[]),month=today().slice(0,7),tx=Array.isArray(data.transactions)?data.transactions:[],debts=Array.isArray(data.debts)?data.debts:[],tasks=Array.isArray(data.tasks)?data.tasks:[];let income=0,expenses=0,todayIn=0,todayOut=0;for(const x of tx){const a=Number(x.amount||0);if(x.date?.slice(0,7)===month){if(x.type==="income")income+=a;else expenses+=a}if(x.date===today()){if(x.type==="income")todayIn+=a;else todayOut+=a}}const dueTasks=tasks.filter((x:any)=>!x.completed&&x.date&&x.date<=today());const upcoming=[...(Array.isArray(planned)?planned:[]).filter((x:any)=>x.status==="planned").map((x:any)=>({name:x.name,amount:Number(x.amount||0),date:x.dueDate})),...debts.filter((x:any)=>x.dueDate&&Number(x.balance||0)>0).map((x:any)=>({name:x.name,amount:Number(x.minimumPayment||x.balance||0),date:x.dueDate}))].filter((x:any)=>{const d=daysUntil(x.date);return d>=0&&d<=7}).sort((a:any,b:any)=>a.date.localeCompare(b.date));const incoming=(Array.isArray(receivables)?receivables:[]).filter((x:any)=>x.status!=="paid"&&x.dueDate&&daysUntil(x.dueDate)>=0&&daysUntil(x.dueDate)<=7);const overdue=[...debts.filter((x:any)=>x.dueDate&&x.dueDate<today()&&Number(x.balance||0)>0),...(Array.isArray(receivables)?receivables:[]).filter((x:any)=>x.status!=="paid"&&x.dueDate&&x.dueDate<today())];return{result:income-expenses,todayIn,todayOut,upcomingTotal:upcoming.reduce((a:any,x:any)=>a+x.amount,0),incomingTotal:incoming.reduce((a:number,x:any)=>a+Number(x.amount||0),0),attention:dueTasks.length+overdue.length,upcoming,incoming,overdue,dueTasks}},[revision]);
 if(!mount||!visible)return null;
 return createPortal(<section className={`today-overview ${s.attention>0?"has-alert":""}`}><div className="today-overview-heading"><div><p className="eyebrow">Overview</p><h2>{s.attention>0?`${s.attention} item${s.attention===1?"":"s"} need attention`:"Everything looks up to date"}</h2></div>{s.attention>0&&<span className="today-status-pill danger">Needs attention</span>}</div><div className="today-overview-grid compact-overview"><article><span>Month result</span><strong className={s.result>=0?"positive-text":"negative-text"}>{euro(s.result)}</strong><small>Current month</small></article><article><span>Today in</span><strong className="positive-text">+{euro(s.todayIn)}</strong><small>Income today</small></article><article><span>Today out</span><strong className="negative-text">−{euro(s.todayOut)}</strong><small>Expenses today</small></article><article><span>Next 7 days</span><strong>{euro(s.upcomingTotal)}</strong><small>{s.upcoming.length} payment{s.upcoming.length===1?"":"s"}</small></article></div><button className="secondary-button overview-more" onClick={()=>setMore(v=>!v)}>{more?"Show less":"Show more"}</button>{more&&<div className="overview-more-grid"><article className="card"><span>Expected income, 7 days</span><strong className="positive-text">{euro(s.incomingTotal)}</strong></article><article className="card"><span>Open tasks / overdue</span><strong>{s.attention}</strong></article>{s.upcoming.slice(0,4).map((x:any,i:number)=><div className="list-row" key={i}><div className="list-content"><strong>{x.name}</strong><span>{x.date}</span></div><strong>{euro(x.amount)}</strong></div>)}</div>}</section>,mount)
}
